# Generated by Django 3.2.4 on 2021-06-29 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 7, 12, 48, 384673, tzinfo=utc)),
        ),
    ]
