# Generated by Django 3.2.4 on 2021-06-29 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_news_fun_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('fun_date', models.DateField(default=datetime.datetime(2021, 6, 29, 7, 33, 59, 21263, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 7, 33, 58, 890575, tzinfo=utc)),
        ),
    ]
