# Generated by Django 3.2.4 on 2021-06-29 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_auto_20210629_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 8, 31, 9, 204942, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 8, 31, 10, 696000, tzinfo=utc)),
        ),
    ]
