# Generated by Django 3.2.4 on 2021-06-29 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_auto_20210629_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=30)),
                ('salary', models.IntegerField(default=100)),
                ('pan', models.CharField(max_length=100)),
                ('req_date', models.DateField(default=datetime.datetime(2021, 6, 29, 10, 49, 20, 195723, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 10, 49, 20, 50119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 10, 49, 20, 194724, tzinfo=utc)),
        ),
    ]
