# Generated by Django 3.2.4 on 2021-06-30 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_auto_20210629_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.IntegerField()),
                ('response', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='infodata',
            name='req_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 8, 57, 14, 85501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 8, 57, 13, 304427, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='fun_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 8, 57, 14, 69879, tzinfo=utc)),
        ),
    ]
